In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [2]:
df = pd.read_csv("public_transport_delays.csv")

In [3]:
df.head()

,trip_id,date,time,transport_type,route_id,origin_station,destination_station,scheduled_departure,scheduled_arrival,actual_departure_delay_min,...,wind_speed_kmh,precipitation_mm,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,season,delayed
0,T00000,2023-01-01,05:00:00,Tram,Route_15,Station_31,Station_6,05:02:00,05:55:00,12,...,46,13.0,NaN,500,81,0,1,6,Winter,0
1,T00001,2023-01-01,05:15:00,Metro,Route_12,Station_49,Station_32,05:16:00,05:55:00,15,...,11,11.4,NaN,0,53,0,0,6,Autumn,1
2,T00002,2023-01-01,05:30:00,Bus,Route_16,Station_29,Station_42,05:33:00,06:17:00,0,...,31,14.1,Sports,0,67,1,0,6,Autumn,0
3,T00003,2023-01-01,05:45:00,Tram,Route_19,Station_26,Station_18,05:49:00,06:08:00,15,...,41,6.4,NaN,500,84,0,0,6,Winter,1
4,T00004,2023-01-01,06:00:00,Tram,Route_8,Station_18,Station_15,06:00:00,06:35:00,-1,...,30,18.5,NaN,500,46,0,0,6,Spring,1

In [4]:
df.columns

Index(['trip_id', 'date', 'time', 'transport_type', 'route_id',
       'origin_station', 'destination_station', 'scheduled_departure',
       'scheduled_arrival', 'actual_departure_delay_min',
       'actual_arrival_delay_min', 'weather_condition', 'temperature_C',
       'humidity_percent', 'wind_speed_kmh', 'precipitation_mm', 'event_type',
       'event_attendance_est', 'traffic_congestion_index', 'holiday',
       'peak_hour', 'weekday', 'season', 'delayed'],
      dtype='str')

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

trip_id                          0
date                             0
time                             0
transport_type                   0
route_id                         0
origin_station                   0
destination_station              0
scheduled_departure              0
scheduled_arrival                0
actual_departure_delay_min       0
actual_arrival_delay_min         0
weather_condition                0
temperature_C                    0
humidity_percent                 0
wind_speed_kmh                   0
precipitation_mm                 0
event_type                    1173
event_attendance_est             0
traffic_congestion_index         0
holiday                          0
peak_hour                        0
weekday                          0
season                           0
delayed                          0
dtype: int64

In [7]:
len(df)

2000

In [8]:
c = df.groupby('event_type')['event_type'].count()
c

event_type
Concert     203
Festival    221
Parade      105
Protest      86
Sports      212
Name: event_type, dtype: int64

In [9]:
df['event_type'].unique()

<StringArray>
[nan, 'Sports', 'Protest', 'Parade', 'Concert', 'Festival']
Length: 6, dtype: str

In [10]:
df['event_type'] = df['event_type'].fillna("NO Event")

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     2000 non-null   str
 1   date                        2000 non-null   str
 2   time                        2000 non-null   str
 3   transport_type              2000 non-null   str
 4   route_id                    2000 non-null   str
 5   origin_station              2000 non-null   str
 6   destination_station         2000 non-null   str
 7   scheduled_departure         2000 non-null   str
 8   scheduled_arrival           2000 non-null   str
 9   actual_departure_delay_min  2000 non-null   int64
 10  actual_arrival_delay_min    2000 non-null   int64
 11  weather_condition           2000 non-null   str
 12  temperature_C               2000 non-null   float64
 13  humidity_percent            2000 non-null   int64
 14  wind_speed_kmh              2000 non-null   int64
 15  precipitation_mm            2000 non-null   float64
 16  event_type                  2000 non-null   str
 17  event_attendance_est        2000 non-null   int64
 18  traffic_congestion_index    2000 non-null   int64
 19  holiday                     2000 non-null   int64
 20  peak_hour                   2000 non-null   int64
 21  weekday                     2000 non-null   int64
 22  season                      2000 non-null   str
 23  delayed                     2000 non-null   int64
dtypes: float64(2), int64(10), str(12)
memory usage: 375.1 KB

In [12]:
pd.to_datetime(df['date'])
pd.to_datetime(df['time'])

C:\Users\praka\AppData\Local\Temp\ipykernel_22600\818874788.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df['time'])

0      2026-04-02 05:00:00
1      2026-04-02 05:15:00
2      2026-04-02 05:30:00
3      2026-04-02 05:45:00
4      2026-04-02 06:00:00
               ...
1995   2026-04-02 23:45:00
1996   2026-04-02 00:00:00
1997   2026-04-02 00:15:00
1998   2026-04-02 00:30:00
1999   2026-04-02 00:45:00
Name: time, Length: 2000, dtype: datetime64[us]

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     2000 non-null   str
 1   date                        2000 non-null   str
 2   time                        2000 non-null   str
 3   transport_type              2000 non-null   str
 4   route_id                    2000 non-null   str
 5   origin_station              2000 non-null   str
 6   destination_station         2000 non-null   str
 7   scheduled_departure         2000 non-null   str
 8   scheduled_arrival           2000 non-null   str
 9   actual_departure_delay_min  2000 non-null   int64
 10  actual_arrival_delay_min    2000 non-null   int64
 11  weather_condition           2000 non-null   str
 12  temperature_C               2000 non-null   float64
 13  humidity_percent            2000 non-null   int64
 14  wind_speed_kmh              2000 non-null   int64
 15  precipitation_mm            2000 non-null   float64
 16  event_type                  2000 non-null   str
 17  event_attendance_est        2000 non-null   int64
 18  traffic_congestion_index    2000 non-null   int64
 19  holiday                     2000 non-null   int64
 20  peak_hour                   2000 non-null   int64
 21  weekday                     2000 non-null   int64
 22  season                      2000 non-null   str
 23  delayed                     2000 non-null   int64
dtypes: float64(2), int64(10), str(12)
memory usage: 375.1 KB

In [14]:
df.columns

Index(['trip_id', 'date', 'time', 'transport_type', 'route_id',
       'origin_station', 'destination_station', 'scheduled_departure',
       'scheduled_arrival', 'actual_departure_delay_min',
       'actual_arrival_delay_min', 'weather_condition', 'temperature_C',
       'humidity_percent', 'wind_speed_kmh', 'precipitation_mm', 'event_type',
       'event_attendance_est', 'traffic_congestion_index', 'holiday',
       'peak_hour', 'weekday', 'season', 'delayed'],
      dtype='str')

In [15]:
df.head()

,trip_id,date,time,transport_type,route_id,origin_station,destination_station,scheduled_departure,scheduled_arrival,actual_departure_delay_min,...,wind_speed_kmh,precipitation_mm,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,season,delayed
0,T00000,2023-01-01,05:00:00,Tram,Route_15,Station_31,Station_6,05:02:00,05:55:00,12,...,46,13.0,NO Event,500,81,0,1,6,Winter,0
1,T00001,2023-01-01,05:15:00,Metro,Route_12,Station_49,Station_32,05:16:00,05:55:00,15,...,11,11.4,NO Event,0,53,0,0,6,Autumn,1
2,T00002,2023-01-01,05:30:00,Bus,Route_16,Station_29,Station_42,05:33:00,06:17:00,0,...,31,14.1,Sports,0,67,1,0,6,Autumn,0
3,T00003,2023-01-01,05:45:00,Tram,Route_19,Station_26,Station_18,05:49:00,06:08:00,15,...,41,6.4,NO Event,500,84,0,0,6,Winter,1
4,T00004,2023-01-01,06:00:00,Tram,Route_8,Station_18,Station_15,06:00:00,06:35:00,-1,...,30,18.5,NO Event,500,46,0,0,6,Spring,1

In [16]:
df.isnull().sum()

trip_id                       0
date                          0
time                          0
transport_type                0
route_id                      0
origin_station                0
destination_station           0
scheduled_departure           0
scheduled_arrival             0
actual_departure_delay_min    0
actual_arrival_delay_min      0
weather_condition             0
temperature_C                 0
humidity_percent              0
wind_speed_kmh                0
precipitation_mm              0
event_type                    0
event_attendance_est          0
traffic_congestion_index      0
holiday                       0
peak_hour                     0
weekday                       0
season                        0
delayed                       0
dtype: int64

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     2000 non-null   str
 1   date                        2000 non-null   str
 2   time                        2000 non-null   str
 3   transport_type              2000 non-null   str
 4   route_id                    2000 non-null   str
 5   origin_station              2000 non-null   str
 6   destination_station         2000 non-null   str
 7   scheduled_departure         2000 non-null   str
 8   scheduled_arrival           2000 non-null   str
 9   actual_departure_delay_min  2000 non-null   int64
 10  actual_arrival_delay_min    2000 non-null   int64
 11  weather_condition           2000 non-null   str
 12  temperature_C               2000 non-null   float64
 13  humidity_percent            2000 non-null   int64
 14  wind_speed_kmh              2000 non-null   int64
 15  precipitation_mm            2000 non-null   float64
 16  event_type                  2000 non-null   str
 17  event_attendance_est        2000 non-null   int64
 18  traffic_congestion_index    2000 non-null   int64
 19  holiday                     2000 non-null   int64
 20  peak_hour                   2000 non-null   int64
 21  weekday                     2000 non-null   int64
 22  season                      2000 non-null   str
 23  delayed                     2000 non-null   int64
dtypes: float64(2), int64(10), str(12)
memory usage: 375.1 KB

In [18]:
df['weather_condition'].unique()

<StringArray>
['Storm', 'Rain', 'Clear', 'Snow', 'Fog', 'Cloudy']
Length: 6, dtype: str

In [19]:
df['season'].unique()

<StringArray>
['Winter', 'Autumn', 'Spring', 'Summer']
Length: 4, dtype: str